name: Presubmit
on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["README", "COPYING", "INSTALL", "NEWS"]'
          do_not_skip: '["pull_request"]'

  build-and-check:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Build and Check Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./bootstrap
      - run: ./configure --enable-official-khronos-headers
      - run: make
      - run: make check
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-and-check
          path: |
            tests/testsuite.log

  distcheck:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Distcheck Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./bootstrap
      - run: ./configure --enable-official-khronos-headers
      - run: make distcheck DISTCHECK_CONFIGURE_FLAGS=--enable-official-khronos-headers

  build-and-check-official-headers:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Build and Check Ubuntu Official Headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        uses: actions/checkout@v2
        with:
          repository: KhronosGroup/OpenCL-Headers
          path: OpenCL-Headers
      - run: ./bootstrap
      - run: ./configure
      - run: make
      - run: make check
        env:
          CPATH: ${{ github.workspace }}/OpenCL-Headers:$CPATH

  distcheck-official-headers:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Distcheck Ubuntu Official Headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        uses: actions/checkout@v2
        with:
          repository: KhronosGroup/OpenCL-Headers
          path: OpenCL-Headers
      - run: ./bootstrap
      - run: ./configure
      - run: make distcheck
        env:
          CPATH: ${{ github.workspace }}/OpenCL-Headers:$CPATH
